/*
 * Copyright (c) 2023, Ignacio Slater M.
 * 2-Clause BSD License.
 */

package cl.ravenhill.keen.prog.terminals

import cl.ravenhill.keen.prog.Environment


/**
 * This class represents an ephemeral constant of generic type T, which is
 * generated by a given generator function.
 * The constant value is generated only once, at initialization time, and remains
 * the same for the lifetime of the object.
 *
 * @param T The generic type of the constant value.
 * @param generator The generator function that generates the constant value of type T.
 * @property contents The constant value of type T.
 *
 * @author <a href="https://www.github.com/r8vnhill">R8V</a>
 * @since 2.0.0
 * @version 2.0.0
 */
data class EphemeralConstant<T>(val generator: () -> T, ) : Terminal<T> {

    private val _value: T? = null
    val value: T get() = _value ?: generator()

    override fun toString() = "$contents"

    override fun create() = EphemeralConstant(generator)
    override fun invoke(environment: Environment<T>, args: List<T>) = value
}