[versions]
kotlin = "2.0.20"
devPublishPlugin = "0.4.1"
jakt = "2.1.0-alpha-3"
kotest = "5.9.1"
detekt = "1.23.6"
coroutines = "1.8.1"
kotlinx-datetime = "0.6.1"
arrow = "2.0.0-alpha.3"
jline = "3.26.3"

### Java compilation ###
# Keen's minimum supported Java version.
jvmMinTarget = "8"
# Keen's maximum supported Java version. (Must be >= jvmMinTarget.)
jvmMaxTarget = "21"
# JDK used to compile Keen. (Must be >= jvmMaxTarget.)
jvmCompiler = "21"
# JDK used to run Gradle Daemon. (Should be the same as jvmCompiler, but could be higher or lower.)
gradleDaemonJvm = "21"

[libraries]
jakt = { module = "cl.ravenhill:jakt", version.ref = "jakt" }

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }

jline = { module = "org.jline:jline", version.ref = "jline" }

# Gradle plugins
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
devPublish-plugin = { module = "dev.adamko.gradle:dev-publish-plugin", version.ref = "devPublishPlugin" }

[plugins]
kotlinBinaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.14.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
