[versions]
kotlin = "2.1.10"
devPublishPlugin = "0.4.2"
jakt = "2.1.0"
kotest = "5.9.1"
kotest-arrow = "2.0.0"
detekt = "1.23.8"
coroutines = "1.10.1"
kotlinx-datetime = "0.6.2"
kotlinx-html = "0.12.0"
arrow = "2.0.1"
jline = "3.29.0"
xchart = "3.8.8"
dokka = "2.0.0"

### Java compilation ###
# Keen's minimum supported Java version.
jvmMinTarget = "8"
# Keen's maximum supported Java version. (Must be >= jvmMinTarget.)
jvmMaxTarget = "21"
# JDK used to compile Keen. (Must be >= jvmMaxTarget.)
jvmCompiler = "21"
# JDK used to run Gradle Daemon. (Should be the same as jvmCompiler, but could be higher or lower.)
gradleDaemonJvm = "21"

[libraries]
jakt = { module = "cl.ravenhill:jakt", version.ref = "jakt" }

kotest-arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-property-arrow = { module = "io.kotest.extensions:kotest-property-arrow", version.ref = "kotest-arrow" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinx-html" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }

jline = { module = "org.jline:jline", version.ref = "jline" }

xchart = { module = "org.knowm.xchart:xchart", version.ref = "xchart" }

# Gradle plugins
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
devPublish-plugin = { module = "dev.adamko.gradle:dev-publish-plugin", version.ref = "devPublishPlugin" }

[plugins]
kotlinBinaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.14.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
