/*
 * Copyright (c) 2024, Ignacio Slater M.
 * 2-Clause BSD License.
 */

package cl.ravenhill.keen.genetics.genes

import cl.ravenhill.keen.Domain
import cl.ravenhill.keen.mixins.Verifiable
import cl.ravenhill.keen.repr.Feature
import kotlin.random.Random


/**
 * Represents a gene in an evolutionary algorithm.
 *
 * The `Gene` interface extends the [Feature] interface, adding functionality specific to genetic algorithms, such as
 * mutation and value generation. A gene is a fundamental unit within a genetic structure (such as a chromosome) and
 * typically represents a single piece of genetic information. This interface defines the core operations that a gene
 * must support, including mutating its value for easier processing within evolutionary algorithms.
 *
 * ## Usage:
 * Implement this interface to create specific types of genes that can be used in genetic algorithms. Each gene
 * should define how its value is generated and how it mutates. The `mutate` function is particularly important for
 * introducing variability into the population during the evolutionary process.
 *
 * ### Example 1: Implementing an Integer Gene
 * ```kotlin
 * data class IntGene(override val value: Int) : Gene<Int, IntGene> {
 *     override val generator: (Random) -> Int = { random -> random.nextInt(0, 100) }
 *
 *     override fun copyWithValue(value: Int) = IntGene(value)
 *     // ... Other gene-specific methods and properties ...
 * }
 * ```
 *
 * ### Example 2: Mutating a Gene
 * ```kotlin
 * val gene = IntGene(42)
 * val mutatedGene = gene.mutate()
 * println(mutatedGene.value) // Output: A new random value generated by the `generator` function
 * ```
 *
 * ### Example 3: Converting a Gene to a List
 * ```kotlin
 * val gene = IntGene(42)
 * val listWithValue = gene.toList()
 * println(listWithValue) // Output: [42]
 * ```
 *
 * ## Recommendation for Functional Programmers:
 * If you are familiar with functional programming and monads, consider implementing subclasses of `Gene` as monads.
 * This can be done by ensuring that your subclass adheres to the monad laws and providing a `pure` (or `unit`) function
 * to wrap values into the monadic structure. Additionally, it is recommended to implement subclasses as data classes
 * to leverage Kotlin's powerful data class features, such as automatic `equals`, `hashCode`, `copy`, and immutability.
 *
 * ### Implementing Subclasses as Monads:
 * 1. **Define a `pure` Function**: This function wraps a value into the monadic structure, ensuring that the gene
 *    adheres to monadic laws.
 *    ```kotlin
 *    companion object {
 *        fun pure(value: Int): IntGene = IntGene(value)
 *    }
 *    ```
 *
 * 2. **Ensure Monad Laws**: Make sure that your subclass respects the left identity, right identity, and associativity
 *    laws. If your subclass doesn't override the `flatMap` function, it should adhere to the monad laws by default.
 *
 * ### Benefits of Using Data Classes:
 * - **Reduced Boilerplate**: Data classes automatically generate `equals`, `hashCode`, `toString`, and `copy` methods,
 *   making your code cleaner and more maintainable.
 * - **Immutability**: Data classes promote immutability, a core principle in functional programming, leading to safer
 *   and more predictable code.
 * - **Convenient Copying**: The `copy` method simplifies the creation of new instances with modified values.
 *
 * @param T The type of the value held by the gene.
 * @param G The type of the gene itself, which must extend [Gene].
 * @property generator A function that generates new values for the gene, typically used in mutation operations.
 */
interface Gene<T, G> : Feature<T, G> where G : Gene<T, G> {

    /**
     * A function that generates new values for the gene.
     *
     * The `generator` function is responsible for producing new values that the gene can hold. This function is
     * typically used during mutation to introduce variability into the gene's value.
     *
     * ### Example:
     * ```kotlin
     * override val generator: (Random) -> Int = { random -> random.nextInt(0, 100) }
     * ```
     */
    val generator: (Random) -> T

    /**
     * Mutates the gene by generating a new value using the `generator` function.
     *
     * The `mutate` function creates a new instance of the gene with a value generated by the `generator` function.
     * This method introduces genetic variability, which is essential for the evolutionary process. The mutation can
     * be influenced by the provided `Random` instance, allowing for controlled randomness in tests or specific
     * scenarios.
     *
     * ### Example:
     * ```kotlin
     * val gene = IntGene(42)
     * val mutatedGene = gene.mutate()
     * println(mutatedGene.value) // Output: A new random value generated by the `generator` function
     * ```
     *
     * @param random The `Random` instance used to generate the new value. Defaults to the global `Domain.random`.
     * @return A new gene instance with the mutated value.
     */
    fun mutate(random: Random = Domain.random): G = copyWithValue(generator(random))
}
